### PR TITLE
Expose number of wheels on raycast vehicle

### PR DESCRIPTION
**Pull request by wuharvey**
This would be useful in https://github.com/pmndrs/racing-game.

Would need to expose in use-cannon too after landing this

### CODE REVIEW

**Comment by marcofugaro** [comment]
Makes sense! Thanks for the PR.

Could you just remove `numWheelsOnGroundTemp` and just use `this.numWheelsOnGround`?

I'll publish on monday.

**Comment by wuharvey** [comment]
Done, thanks for the quick turnaround!

**Comment by wuharvey** [comment]
Sorry to pester - will this get published today?

**Review by marcofugaro — APPROVED** [review]
Doing it now!

**Pull request merged**
