### PR TITLE
Fix: Friction disappears when manually applying gravity #224

### PR DESCRIPTION
**Pull request by chnicoloso**
Addresses:
https://github.com/schteppe/cannon.js/issues/224

Reuses pattern from p2.js:
https://github.com/schteppe/p2.js/blob/master/src/world/World.js#L88-L92

Before:
ezgif com-gif-maker (1)

After:
ezgif com-gif-maker

### CODE REVIEW

**Comment by chnicoloso** [comment]
cc @marcofugaro @codynova (you surface as recent contributors, hoping I can get a review from one of you, thank you!)

**Comment by isaac-mason** [comment]
Thanks for this! 🙂 

One comment from me:

If `world.gravity` is changed after construction, `world.frictionGravity` won't update. As-is, users would need to update both, which is a backwards incompatible change. 

Maybe we could add flags such as the `world.useWorldGravityAsFrictionGravity` and `useFrictionGravityOnZeroGravity` flags in p2 to solve this?

Let me know what you think.

**Comment by chnicoloso** [comment]
@isaac-mason thanks for having a look! 

Ah yes, thank you! Great catch. The flags are a good idea, though I would prefer an approach that kept the config matrix as small and simple as possible. How about this:

- By default, `world.frictionGravity` is undefined.
- `Narrowphase` applies friction using `world.frictionGravity || world.gravity`.

This way, current behavior is maintained and backwards compatibility is ensured while still allowing users to override friction gravity, if they need to. When the average user changed `world.gravity`, friction would change with it, no surprises - only users who have explicitly set `world.frictionGravity` would be expected to manually manage that relationship between `world.gravity` and `world.frictionGravity`. 

What do you think?

**Comment by chnicoloso** [comment]
I updated with the suggestion above. Also, I noticed that `dist/` is not in the project's `.gitignore`. Am I supposed to be building and committing the built package or is there a build/deploy pipeline that takes care of that?

**Comment by isaac-mason** [comment]
@chnicoloso that sounds reasonable to me! I'll give this another read-through shortly 🙂

**Comment by isaac-mason** [comment]
I believe right now builds are committed to `dist` on doing a release? Would want someone else to confirm that though.

**Comment by isaac-mason** [comment]
Implementation LGTM! `readme.md` just needs updating to reflect the new approach.

**Comment by isaac-mason** [comment]
Could anyone else also give this a review? @marcofugaro / @codynova

**Comment by chnicoloso** [comment]
Thanks @isaac-mason! I updated the `readme` - will hold on building and committing `dist` until we get confirmation that this is indeed what we want.

**Comment by drcmda** [comment]
i can merge and publish if you guys want? i don't understand the code but from looking at the images it behaves correct.

**Comment by chnicoloso** [comment]
THanks @drcmda! That would be great - so you _don't_ need me to build and commit `dist`?

**Review by marcofugaro — APPROVED** [review]
Makes sense, thanks!

**Comment by marcofugaro** [comment]
Yeah, we would need an example, but maybe in a future PR if someone wants

**Pull request merged**
