### PR TITLE
Update examples code

### PR DESCRIPTION
**Pull request by marcofugaro**
When adjusting the cylinder orientation to the new one, I discovered that the examples are implemented in the `Z up left-handed` coordinate system.
This PR updates the examples to use the OpenGL and WebGL standard coordinate system `Y up right-handed`.

While at it i decided also to
- replace `TrackballControls` with `OrbitControls`, they make more sense
- convert the examples to modern ES6 syntax

The visual result should be the same, since only the code changes.

### CODE REVIEW

**Comment by codynova** [comment]
This is awesome, I think it will be much easier for newcomers to understand the coordinate system

**Comment by codynova** [comment]
I didn't read this clearly the first time. The ES6 conversion is even more awesome than the adjusted coordinates. I'm super excited to have this.

**Comment by marcofugaro** [comment]
@codynova this PR is finally ready for review 🥳

**Comment by codynova** [comment]
Amazing work, this is massive 🎺

**Review by codynova — APPROVED** [review]

**Pull request merged**
