### PR TITLE
Add documentation with Typedoc again

### LINKED ISSUE #12: Documentation website
Hey all!

Arriving from https://github.com/schteppe/cannon.js/issues/438 and very happy to  see a fork actively maintanted. 

The README here still says "Visit the original project for full documentation and examples." but the reality is the original project is "[...] slowly disintegrating. Piece by piece." :-D 

I see everything is typescripted now, so there must be some good tools out there now, better than YUI for sure!

How can we help get this documentation website up?

### PR DESCRIPTION
**Pull request by marcofugaro**
Close #12 

This PR is a continuation of #14, it uses the newer beta of Typedoc being developed in https://github.com/TypeStrong/typedoc/issues/1364.

# [Preview of the docs here](https://raw.githack.com/pmndrs/cannon-es/typedoc2/docs/index.html)

## Things to fix

- [x] Show the class params in the class page.

Currently the class params are not being shown,

this is probably because the JSDoc @param definition is not supported in Typedoc

However they are being shown in the homepage, which is not the correct place for them

I guess this is because the type `BodyOptions` is exported directly?

- [x] Class properties and methods comments are not shown

This is because the comment are currently in line format:

They need to be in JSDoc format:

## UI/UX Improvements

- [x] Disable the header scroll-up behaviour, it is annoying 
- [x] Hide the `All` and `Only exported` keys, we don't use them in this project

### CODE REVIEW

**Comment by stockHuman** [comment]
Hey @marcofugaro, I can help out with this in my spare time, and push AABB unless you had other plans. :)

**Comment by marcofugaro** [comment]
❤️❤️
thanks @stockHuman any help is appreciated, commits https://github.com/pmndrs/cannon-es/pull/54/commits/8cf2711566291de4f485b6d7e5360718b06f7205#diff-a0a9650986b438fd092671e05a98fb560e381188460824affdf3a41a97bef0f0 and https://github.com/pmndrs/cannon-es/pull/54/commits/b1ff14a3a435d6c88b6e4e3187e9dd555226d854 should help you get started.

Basically here is what you do:

- convert `//` comments to `/**` comments for class properties
- put static methods/properties in the class
- remove any `@method` jsdoc annotation in the class methods
- remove every jsdoc annotation except `@example` in the class jsdoc comment
- move the options type in the constructor and export the type like this `export type SpringOptions = ConstructorParameters<typeof Spring>[2]`

In the meantime I was working on updating the examples to three 0.125 and researching a better way of doing the BufferGeometry to ConvexGeometry conversion in the branch [`three-update`](https://github.com/pmndrs/cannon-es/tree/three-update)

**Comment by stockHuman** [comment]
@marcofugaro Yeah - I saw b1ff14a - it's very helpful. :)

I completely missed the r125 branch; I guess the pull to fix use-cannon can wait on whatever we settle on as I quite like being able to simply pass geometries to convexPolyhedron.

**Comment by marcofugaro** [comment]
🤩 amazing work @stockHuman thanks a lot!

Just an issue, could you leave out of this PR the stuff non related to JSDoc? Such as using an inline `Vec3` here. I believe the `Vec3` is saved outside of the class for memory reasons.


This is the diff of the stuff you did, if it's useful https://github.com/pmndrs/cannon-es/compare/b1ff14a...pmndrs:0b81356

**Comment by stockHuman** [comment]
I'm getting `this.emitContactEvents is not a function` in the examples, coming from within `World`. This seems to predate my changes (present in b1ff14a), but working as intended by ac7a1f2.

**Comment by stockHuman** [comment]
> Just an issue, could you leave out of this PR the stuff non related to JSDoc? Such as using an inline `Vec3` here. I believe the `Vec3` is saved outside of the class for memory reasons.

Sure thing, will undo. :)

**Comment by marcofugaro** [comment]
Little typo at line 37 of `RaycastVehicle.ts`

image

**Comment by marcofugaro** [comment]
> I'm getting this.emitContactEvents is not a function in the examples, coming from within World. This seems to predate my changes (present in b1ff14a), but working as intended by ac7a1f2.

Ummm, will look into this

**Comment by stockHuman** [comment]
> 
> 
> Little typo at line 37 of `RaycastVehicle.ts`
> 
> image

Embarrassing, lol.

**Comment by marcofugaro** [comment]
Thanks for the amazing work @stockHuman!! I'll take it from here, fix the latest issue and solve conflicts in next few days.

**Comment by stockHuman** [comment]
Awesome, glad I could help. :)

**Comment by marcofugaro** [comment]
The documentation is done! 🎉

Preview: https://raw.githack.com/pmndrs/cannon-es/typedoc2/docs/index.html

Ended up enabling the `excludeNotDocumented` option to hide all internal stuff, but that meant adding a jsdoc comment to all methods that need to be exposed. It is done!

Only thing to fix is the build issue, it's pretty straightforward, will fix it soon.

**Pull request merged**
