### PR TITLE
Port tests for World class from Cannon.js

### PR DESCRIPTION
**Pull request by patreeceeo**
Simply converts them to ES and Jest. I could see opportunities to make the test code more DRY, but wanted to get a second opinion before attempting that. Also I'd probably need a deeper understanding of the app code to do that.

As a side note: I stumbled upon a possible Jest bug in which the runner hangs and complains about circular references. Only happened when I tried to add an assertion that wasn't in the original tests. It occurs when running the entire test suite rather than one file and using the toBe matcher between two Body instances that fails. Briefly searched for open bug reports to no avail.

### CODE REVIEW

**Comment by marcofugaro** [comment]
Sorry for the late review, I was busy.

Your PR is giving me these issues with the `typegen` script, does it happen to you as well?

PS I added a jest.config.js and upgraded some devDeps that were causing troubles on installations, could you do a rebase?

image

The PR is nice BTW, I really like `toBeColliding()`, could it be used elsewhere other than in `testCollisionMatrix`?

**Comment by patreeceeo** [comment]
Yup I see those errors too, I'll see if I can fix. 

I did a merge of master out of habit, I can do a rebase though if that's important. 

The toBeColliding matcher should be accessable in any test, though the data structures it uses currently might be particular to that file. Hard for me to say, yet.

**Comment by marcofugaro** [comment]
> I did a merge of master out of habit, I can do a rebase though if that's important.

Merge is fine too

> The toBeColliding matcher should be accessable in any test, though the data structures it uses currently might be particular to that file. Hard for me to say, yet.

I see, we might leave the helper in World.test.ts if it's only needed there, but for now it's fine how you did it.

PS could you move the `setupFilesAfterEnv` in the `jest.config.js` now that it's present?

**Comment by patreeceeo** [comment]
How's that?

**Review by marcofugaro — APPROVED** [review]

**Comment by marcofugaro** [comment]
Thanks @patreeceeo! Good job!
In the end I choose to keep your original solution, it seems more scalable. Let's see how it goes with the other tests!

**Pull request merged**
