### PR TITLE
Rename .computeAABB() to .updateAABB();

### PR DESCRIPTION
**Pull request by Cloud9c**

### CODE REVIEW

**Comment by marcofugaro** [comment]
Hello, could you motivate the reason behind this PR?

**Comment by Cloud9c** [comment]
Changing computeAABB() to updateAABB() for the Body class has been on the todo for a while. Also, the current format is computeX() and updateX(), where computeX() usually has parameters and returns a value, while updateX() has no parameters and changes internal variables. computeAABB does not return anything or accept parameters, and instead updates the internal AABB for the body. Therefore, I think it makes more sense to change it to updateAABB().

**Comment by marcofugaro** [comment]
True, it was as @todo in a jsdoc comment.

However I don't know about this one, [three.js uses the word compute for these kind of methods](https://threejs.org/docs/index.html#api/en/core/BufferGeometry.computeBoundingBox).

What do you guys think @stockHuman @codynova?

**Comment by codynova** [comment]
I do think it makes sense to bring the method name inline with the other patterns throughout Cannon, but I also see value in bringing our method names more inline with Three. We could consider changing our other update method names to be closer to the pattern in Three, but that seems like it could cause a lot of churn, and we'd have to rethink our method naming scheme. Let's see what Mike thinks. @marcofugaro I think you get the final decision.

**Comment by stockHuman** [comment]
Hey folks. As when I first saw this issue, I still broadly agree with the change & can now echo Cody.
Re: other methods, as much as Three is a natural complement to Cannon, this lib isn't an ecosystem add-on but instead its own thing, so having internally-consistent names that aren't necessarily mapped to Three's sounds fine by me.

I'd go ahead an honour the old _todo_.

**Comment by marcofugaro** [comment]
Right, didn't notice that in the Body the pattern was `update`, let's change it!

**Pull request merged**
