### PR TITLE
Add documentation with Typedoc

### LINKED ISSUE #12: Documentation website
Hey all!

Arriving from https://github.com/schteppe/cannon.js/issues/438 and very happy to  see a fork actively maintanted. 

The README here still says "Visit the original project for full documentation and examples." but the reality is the original project is "[...] slowly disintegrating. Piece by piece." :-D 

I see everything is typescripted now, so there must be some good tools out there now, better than YUI for sure!

How can we help get this documentation website up?

### PR DESCRIPTION
**Pull request by marcofugaro**
Added Typedoc and generated the default website for now, you can preview it with `npx serve docs/`.

Here are the things that still need to be fixed in this PR:

- [x] Ignore modules and just list classes, related to [this Typedoc PR](https://github.com/TypeStrong/typedoc/pull/1184)
It should go from this
image
To something like this
image

- [ ] Class parameters are not shown

However are shown in the module, so this is probably related to previous issue

- [ ] Properties and methods comments are not shown
image

- [ ] Minor UX and UI adjustments

Close #12

### CODE REVIEW

**Comment by sean-codes** [comment]
Is there any update / work being done on this topic? Is there cannon-es documentation anywhere? Currently using http://schteppe.github.io/cannon.js/docs/ but some of the method names are different and argument differences.

**Comment by marcofugaro** [comment]
@sean-codes we're currently blocked by this Typedoc PR https://github.com/TypeStrong/typedoc/pull/1184, with Typedoc being the only documentation website builder for typescript and currently isn't working very well with libraries.

In the meantime, yes you can refer to the old cannon.js documentation and the list of changes done to cannon-es explained in the README 🙂

**Comment by hmans** [comment]
I would like to make the case for setting the typedoc mode to `file` and merging this instead of waiting for https://github.com/TypeStrong/typedoc/pull/1184. That issue has been open for a long, long time, and having the updated docs contained in this PR here will provide immediate value, both to users of cannon-es and to people who intend to contribute to it.

The resulting documentation looks fine -- and unless I'm missing something obvious, is at least as good as the old (and in parts outdated) Cannon.js documentation this repository has been referring people to.

image

**Comment by marcofugaro** [comment]
@hmans yeah you're right, the documentation is needed.

I've updated this PR in #54 with the new beta of Typedoc, the main issues have been solved.
However there is still a big issue with the class options not being shown, probably is due to some weirdly structured JSDoc comments, we should try changing the comments someway and see if they are shown.

More details in #54, the docs will be acceptable when that issue will be fixed, and I will make that PR ready for review. Any help is appreciated, if you find the solution you could tell me or make a PR against that branch.

There are a couple of small issues, but we can merge and do that later.

------------------------

Example of the empty body class:

https://raw.githack.com/pmndrs/cannon-es/typedoc2/docs/classes/body.html




Closing in favor of #54

**Pull request closed without merging**
